#!/usr/bin/env node
/**
 * Writes src-tauri/tauri.updater.conf.json for whichever repository is building.
 *
 *   node scripts/updater-config.mjs
 *
 * The endpoint is derived from GITHUB_REPOSITORY when running in Actions, and
 * from the git "origin" remote otherwise, so a fork updates from its own
 * releases without anyone editing a URL. The public key comes from
 * TAURI_SIGNING_PUBLIC_KEY; without it the script writes nothing and exits 0,
 * which lets a repository without signing secrets keep publishing normally —
 * just without the in-app updater.
 */

import { rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { repositorySlug } from "./repo-slug.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const TARGET = join(ROOT, "src-tauri", "tauri.updater.conf.json");

// Re-exported because this module used to own it and the tests import it here.
export { repositorySlugFromRemote } from "./repo-slug.mjs";

export function updaterSigningMode(publicKey, privateKey) {
  const hasPublicKey = Boolean(publicKey?.trim());
  const hasPrivateKey = Boolean(privateKey?.trim());

  if (hasPublicKey !== hasPrivateKey) {
    throw new Error(
      "TAURI_SIGNING_PUBLIC_KEY and TAURI_SIGNING_PRIVATE_KEY must either both be set or both be absent.",
    );
  }

  return hasPublicKey ? "enabled" : "disabled";
}

export function main() {
  const pubkey = process.env.TAURI_SIGNING_PUBLIC_KEY?.trim();
  const privateKey = process.env.TAURI_SIGNING_PRIVATE_KEY?.trim();
  const mode = updaterSigningMode(pubkey, privateKey);

  // A local build must never inherit configuration generated by an earlier
  // signed build.
  rmSync(TARGET, { force: true });

  if (mode === "disabled") {
    process.stdout.write(
      "Updater signing keys are not set; building without the updater.\n" +
        "Generate a key pair with `pnpm tauri signer generate -w .tauri/qmo.key`.\n",
    );
    return;
  }

  const slug = repositorySlug();
  const config = {
    $schema: "../node_modules/@tauri-apps/cli/config.schema.json",
    bundle: { createUpdaterArtifacts: true },
    plugins: {
      updater: {
        pubkey,
        endpoints: [
          `https://github.com/${slug}/releases/latest/download/latest.json`,
        ],
        windows: { installMode: "passive" },
      },
    },
  };

  writeFileSync(TARGET, `${JSON.stringify(config, null, 2)}\n`);
  process.stdout.write(`Updater will check ${config.plugins.updater.endpoints[0]}\n`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
